[dev]
command = "npx snowpack dev"
framework = "#custom"
targetPort = 3000
#autoLaunch = false

[build]
functions = "functions"
publish = "build"

[[redirects]]
from = "/api/*"
status = 200
to = "/.netlify/functions/:splat"
