
type Query {
  feedDocuments(id: String, ts: Long, limit: Int!): [Document!]!
    @resolver(name: "feed_documents")
}

type Mutation {
  setDocument(document: DocumentInput): Document
    @resolver(name: "set_document")
}

type Document {
  stringData: String
  booleanData: Boolean
  numberData: Float

  id: String!
  updatedAt: Long!
  deleted: Boolean!
}

input DocumentInput {
  stringData: String
  booleanData: Boolean
  numberData: Float

  id: String!
  updatedAt: Long!
  deleted: Boolean!
}